stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login docker.io -u illona -p videgrenier
    - docker build -t illona/60f2559a334b:29c264445db9 .
    - docker push illona/60f2559a334b:29c264445db9

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker run -d -p 8000:80 illona/php:29c264445db9
    - sleep 10 # Attendre que le conteneur soit prêt
    - curl http://127.0.0.1:8000

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  only:
    - main
  when: manual

deploy-rec:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: recette
  only:
    - stage
  when: manual

deploy-dev:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: developpement
  only:
    - develop
  when: manual
