stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login docker.io -u illona -p videgrenier

    - docker build -t illona/60f2559a334b:29c264445db9 . # php
    - docker build -t illona/8ee9858477ab:1eba4c9bcaa8 . # mysql
    - docker build -t illona/60f2559a334b:933569f3a9f6 . # phpmyadmin
    - docker build -t illona/8ee9858477ab:bb7290db0071 . # composer

    - docker push illona/60f2559a334b:29c264445db9 # php
    - docker push illona/8ee9858477ab:1eba4c9bcaa8 # mysql
    - docker push illona/60f2559a334b:933569f3a9f6 # phpmyadmin
    - docker push illona/8ee9858477ab:bb7290db0071 # composer


trigger-child-pipeline:
  stage: test
  trigger:
    include: .child-pipeline.yml
    strategy: depend

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  only:
    - main
  when: manual

deploy-rec:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: recette
  only:
    - stage
  when: manual

deploy-dev:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: developpement
  only:
    - develop
  when: manual
