version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: phpvidegrenier
    ports:
      - 8000:80
    restart: always
    working_dir: /public
    volumes:
      - /default.conf:/var/www/html
    build: 
      context: .
      dockerfile: Dockerfile

  composer:
    image: composer:latest
    command: composer install --ignore-platform-reqs --no-interaction
    volumes:
      - .:/App
    working_dir: /App

# Ne pas faire tant que le php n'est pas ok
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbvidegrenier
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    ports:
      - 3300:3306


  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSEWORD: 0605
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80

#volumes:
 # mysql_data: {}