services:
  php:
    image: php:8.2-apache
    container_name: php82videgrenier
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
